import NavBar from '@/components/NavBar'
import RandomImageComponent from '@/components/RandomImage'
import RandomQuote from '@/components/Randomquote'
import Head from 'next/head'
import MusicPlayer from '@/components/MusicPlayer'

const trackList = [
  { title: 'Track 1', src: '/carlcox.mp3', title: 'carl cox melbourne', srcImg:'/favicon.ico' },
  { title: 'Track 2', src: '/carlcox.mp3' },
  { title: 'Track 3', src: '/carlcox.mp3' },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar/>
        <RandomImageComponent/>
        <RandomQuote/>
        <MusicPlayer trackList={trackList}/>
      </div>
    </>
  )
}
